### ISSUE TITLE
Project Documentation

### ISSUE THREAD

**Issue by Zakor11** [mif-sge/organisation#1]
Depends on:
- [x] mif-sge/verkehr#6
- [x] mif-sge/verkehr#7
- [x] mif-sge/verkehr#9
- [x] mif-sge/verkehr#15 
- [x] mif-sge/krankenhaus#3
- [x] mif-sge/krankenhaus#4
- [x] mif-sge/krankenhaus#7
- [x] mif-sge/krankenhaus#9
- [x] mif-sge/einkaufszentrum#1
- [x] mif-sge/einkaufszentrum#2

**Comment by xTeufelx** [comment]
The following use cases are missing:
- [ ] [UC-VN-2.1, UC-VN-2.2 and UC-VN-2.3](https://github.com/mif-sge/verkehr/blob/dev/Documentation/Use%20Cases/Use-Case-Diagram_UC-VN-2.png)
- [ ] [UC-VN-3.1, UC-VN-3.2 and UC-VN-3.2](https://github.com/mif-sge/verkehr/blob/dev/Documentation/Use%20Cases/Use-Case-Diagram_UC-VN-3.png)

**Comment by Zakor11** [comment]
thanks, should be integrated now as of commit 88f6d118befcfb1c94e0ab61afefef2b61c310d5

**Comment by Zakor11** [comment]
finished adding mif-sge/verkehr#15 with commit 80f4e6f02956e4944bfb70efb13aa91216fecd80

**Comment by xTeufelx** [comment]
- chapter 4.1, Node.js and npm are listed twice
- chapter 4.2, typo (Tymannm)

**Comment by AlexJ2017** [comment]
Findings of review:
- [ ] Denglisch in Usecases
- [ ] UseCase TrafficNode: User -> Bürger
- [ ] UseCase TrafficNode: Organism isn't human
- [ ] Login Screen Passwort leftbound
- [ ] StructureDiag Hospital "Cental" Node Typo

**Comment by AlexJ2017** [comment]
[ ] Build Doxyfile of SmartCityOrganism-Softwarespezifikation.md

**Comment by Zakor11** [comment]
Fixed all findings as of commit b12c6a5

**Comment by Zakor11** [comment]
Implemented last documentation details as of  commit 060f6be
